#
/run/initialize
# Use this open statement to create an OpenGL view:
/vis/open OGL 600x400-0+0

/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify zoom value:
/vis/viewer/zoom 10.
#
# Specify style (surface or wireframe):
/vis/viewer/set/style surface
#
# Draw coordinate axes:
#/vis/scene/add/axes 0 0 0 1 m
#
# To superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

/vis/viewer/set/globalLineWidthScale 2
/vis/scene/add/trajectories rich

/vis/viewer/set/viewpointThetaPhi 0 90 deg
/vis/viewer/set/background white
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add anti_nu_e
/vis/filtering/trajectories/particleFilter-0/invert true
/vis/viewer/set/lineSegmentsPerCircle 100

/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 1


/vis/modeling/trajectories/drawByCharge-0/default/setLineWidth 2

# to remove tracks in the seed
#/vis/filtering/trajectories/create/encounteredVolumeFilter
#/vis/filtering/trajectories/encounteredVolumeFilter-0/add seed
#/vis/filtering/trajectories/encounteredVolumeFilter-0/invert true

#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/set e- mediumaquamarine
#/vis/modeling/trajectories/drawByParticleID-0/set alpha darkorchid
#/vis/modeling/trajectories/drawByParticleID-0/default/setLineWidth 2

# add scale 

#/vis/scene/add/scale 1 mm x 0 0 0 manual 1 -1 0 mm
#/vis/scene/endOfEventAction accumulate 500